@extends('frontend.layouts.app', ['bodyClass' => 'page-recruitment'])

@section('content')
<div class="container px-3 mx-auto pt-5 lg:pt-8"><x-breadcrumb :items="[['label' => 'Trang chủ', 'url' => route('home')], ['label' => 'Tuyển dụng']]" /></div>
<section class="section section-recruitment-hero py-8 sm:py-12 relative overflow-hidden">
    <div class="container px-3 mx-auto grid items-center gap-9 lg:grid-cols-2 lg:gap-16">
        <div><x-theme.badge text="Cơ hội nghề nghiệp" /><h1 class="text-3xl font-extrabold leading-tight text-black sm:text-4xl lg:text-5xl">Gia Nhập Đội Ngũ Chuyên Gia Môi Trường Bảo Châu</h1><p class="mt-5 text-lg leading-relaxed text-gray-600">Cùng xây dựng những giải pháp môi trường có giá trị thực tế và phát triển sự nghiệp trong một đội ngũ chuyên môn cao.</p><a href="#vi-tri-tuyen-dung" class="mt-7 inline-flex rounded-full bg-primary px-6 py-3 font-bold text-white">Xem vị trí đang tuyển</a><div class="mt-8 grid grid-cols-3 gap-3">@foreach ([['20+', 'Chuyên gia'], ['7', 'Vị trí mở'], ['3', 'Văn phòng']] as [$number, $label])<div class="rounded-2xl bg-white p-4 text-center shadow-sm"><strong class="block text-2xl text-primary">{{ $number }}</strong><span class="text-xs font-semibold text-gray-600">{{ $label }}</span></div>@endforeach</div></div>
        <img src="{{ asset('assets/images/moi-truong-bao-chau-1024x603.jpg') }}" width="1024" height="603" fetchpriority="high" decoding="async" alt="Cơ hội nghề nghiệp tại Môi Trường Bảo Châu" class="w-full rounded-[2rem] object-cover shadow-xl">
    </div>
</section>
<section class="section section-benefits py-10 lg:py-16 relative overflow-hidden bg-gray-50/70">
    <div class="container px-3 mx-auto"><div class="mb-10 text-center"><x-theme.badge text="Môi trường làm việc" class="justify-center" /><h2 class="text-2xl font-extrabold leading-tight text-black sm:text-3xl lg:text-4xl">Vì Sao Bạn Nên Chọn Đồng Hành Cùng Bảo Châu?</h2></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach ([['Phát triển chuyên môn', 'Được tham gia dự án thực tế và học hỏi từ chuyên gia giàu kinh nghiệm.'], ['Lộ trình rõ ràng', 'Đánh giá minh bạch, cơ hội phát triển theo năng lực và đóng góp.'], ['Văn hóa đồng hành', 'Tôn trọng, chủ động, chia sẻ kiến thức và hỗ trợ lẫn nhau.'], ['Giá trị bền vững', 'Công việc tạo tác động tích cực cho doanh nghiệp và cộng đồng.']] as [$title, $description])<article class="rounded-3xl border border-black/8 bg-white p-6 shadow-sm"><span class="mb-4 flex size-12 items-center justify-center rounded-2xl bg-emerald-100 text-primary">✓</span><h3 class="text-xl font-bold">{{ $title }}</h3><p class="mt-3 leading-relaxed text-gray-600">{{ $description }}</p></article>@endforeach</div></div>
</section>
<section id="vi-tri-tuyen-dung" class="section section-jobs py-12 lg:py-20 relative overflow-hidden bg-gray-50/30">
    <div class="container px-3 mx-auto"><div class="mb-10 text-center"><x-theme.badge text="Cơ hội hiện tại" class="justify-center" /><h2 class="text-3xl font-extrabold leading-tight text-black sm:text-4xl lg:text-5xl">Các vị trí tuyển dụng</h2></div><div class="grid gap-4">@forelse ($jobs as $job)<article class="grid items-center gap-5 rounded-3xl border border-black/8 bg-white p-6 shadow-sm md:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold uppercase tracking-wide text-primary">{{ $job->employment_type }} · {{ $job->location }}</p><h3 class="mt-2 text-xl font-bold text-gray-900 sm:text-2xl"><a href="{{ route('recruitment.show', $job->slug) }}" class="hover:text-primary">{{ $job->title }}</a></h3><p class="mt-2 text-gray-600">{{ $job->summary }}</p></div><a href="{{ route('recruitment.show', $job->slug) }}" class="rounded-full bg-secondary px-5 py-3 text-center font-bold text-white">Xem chi tiết</a></article>@empty<p class="text-center">Hiện chưa có vị trí tuyển dụng mới.</p>@endforelse</div><div class="mt-10">{{ $jobs->links() }}</div></div>
</section>
<section class="section section-process py-10 lg:py-16 relative overflow-hidden">
    <div class="container px-3 mx-auto"><div class="mb-10 text-center"><x-theme.badge text="Quy trình tuyển dụng" class="justify-center" /><h2 class="text-2xl font-extrabold leading-tight text-black sm:text-3xl lg:text-4xl">Hành Trình Gia Nhập Bảo Châu</h2></div><ol class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach ([['01', 'Gửi hồ sơ'], ['02', 'Trao đổi sơ bộ'], ['03', 'Phỏng vấn chuyên môn'], ['04', 'Nhận việc & hội nhập']] as [$step, $label])<li class="rounded-3xl border border-black/8 bg-white p-6 text-center shadow-sm"><strong class="text-4xl text-primary">{{ $step }}</strong><h3 class="mt-4 font-bold">{{ $label }}</h3></li>@endforeach</ol></div>
</section>
<section id="form-ung-tuyen" class="section section-apply py-12 lg:py-20 relative overflow-hidden bg-gray-50/70">
    <div class="container px-3 mx-auto grid gap-8 lg:grid-cols-2 lg:gap-14"><div><x-theme.badge text="Ứng tuyển ngay" /><h2 class="text-2xl font-extrabold leading-tight text-black sm:text-3xl lg:text-4xl">Sẵn Sàng Cho Bước Ngoặt Sự Nghiệp?</h2><p class="mt-5 text-lg leading-relaxed text-gray-600">Gửi thông tin để phòng nhân sự liên hệ và hướng dẫn cách nộp CV phù hợp với vị trí bạn quan tâm.</p><div class="mt-7 rounded-3xl border border-black/8 bg-white p-6"><p class="font-bold text-secondary">Phòng Nhân sự Môi Trường Bảo Châu</p><p class="mt-3">Hotline: <a href="tel:0915549148" class="text-primary">0915 549 148</a></p><p>Email: <a href="mailto:info@baochauenvir.com" class="text-primary">info@baochauenvir.com</a></p></div></div><form action="{{ route('contact.store') }}" method="post" class="grid gap-5 rounded-[2rem] border border-black/8 bg-white p-6 shadow-lg sm:grid-cols-2 sm:p-8">@csrf<input type="hidden" name="topic" value="Ứng tuyển"><div class="hidden" aria-hidden="true"><label for="recruitment-website">Website</label><input id="recruitment-website" name="website" tabindex="-1" autocomplete="off"></div><div><label for="candidate-name" class="mb-2 block font-bold">Họ và tên</label><input id="candidate-name" name="name" required class="w-full rounded-2xl border border-gray-300 px-4 py-3"></div><div><label for="candidate-phone" class="mb-2 block font-bold">Số điện thoại</label><input id="candidate-phone" name="phone" type="tel" required class="w-full rounded-2xl border border-gray-300 px-4 py-3"></div><div class="sm:col-span-2"><label for="candidate-email" class="mb-2 block font-bold">Email</label><input id="candidate-email" name="email" type="email" class="w-full rounded-2xl border border-gray-300 px-4 py-3"></div><div class="sm:col-span-2"><label for="candidate-message" class="mb-2 block font-bold">Vị trí quan tâm & giới thiệu ngắn</label><textarea id="candidate-message" name="message" rows="5" required class="w-full rounded-2xl border border-gray-300 px-4 py-3"></textarea></div><div class="sm:col-span-2"><button type="submit" class="w-full rounded-full bg-primary px-6 py-3 font-bold text-white">Gửi thông tin ứng tuyển</button></div></form></div>
</section>
<x-theme.partners title="Môi Trường Bảo Châu – Đồng Hành Cùng Hơn 500+ Doanh Nghiệp" />
@endsection
